### ISSUE TITLE
Can you make it support promise???

### ISSUE THREAD

**Issue by SiwakornSitti** [pipedrive/client-nodejs#38] opened 2017-01-10 08:37 UTC

**Comment by chemdrew** [comment] 2017-01-13 21:03
http://bluebirdjs.com/docs/api/promise.promisifyall.html

Promise.promisifyAll(pipedrive.Activities);
Promise.promisifyAll(pipedrive.ActivityTypes);
Promise.promisifyAll(pipedrive.Authorizations);
Promise.promisifyAll(pipedrive.Currencies);
Promise.promisifyAll(pipedrive.Deals);
Promise.promisifyAll(pipedrive.DealFields);
Promise.promisifyAll(pipedrive.Files);
Promise.promisifyAll(pipedrive.Filters);
Promise.promisifyAll(pipedrive.Notes);
Promise.promisifyAll(pipedrive.Organizations);
Promise.promisifyAll(pipedrive.OrganizationFields);
Promise.promisifyAll(pipedrive.Persons);
Promise.promisifyAll(pipedrive.PersonFields);
Promise.promisifyAll(pipedrive.Pipelines);
Promise.promisifyAll(pipedrive.Products);
Promise.promisifyAll(pipedrive.ProductFields);
Promise.promisifyAll(pipedrive.SearchResults);
Promise.promisifyAll(pipedrive.Stages);
Promise.promisifyAll(pipedrive.Users);

lol

**Comment by meetbryce** [comment] 2017-01-23 10:28
I found [this Stackoverflow helpful](http://stackoverflow.com/questions/22519784/how-do-i-convert-an-existing-callback-api-to-promises)

Here's how I implemented their suggestion:
```javascript
return new Promise((resolve, reject) => { // Shims old school NodeJS callback approach as ES6 Promise
  pipedrive.Deals.getAll({ filter_id }, (err, data) => {
    if (err !== null) return reject(err);
      resolve(data);
    });
}).catch((err) => console.log('ERROR ==>', err));
```

**Comment by lprhodes** [comment] 2017-04-04 03:17
```
const promiseFuncs = [ 'Deals', 'Notes', 'Organizations', 'Persons' ]

promiseFuncs.forEach((funcName) => {
  pipedrive[funcName] = Promise.promisifyAll(pipedrive[funcName])
})
```

**Comment by IgorHalfeld** [comment] 2019-02-08 18:24
Check out this #84

**Comment by tot-ra** [comment] 2019-11-01 08:29
Duplicate of https://github.com/pipedrive/client-nodejs/issues/81

**Closed by tot-ra** 2019-11-01 08:29 UTC
Labels: enhancement
