### ISSUE TITLE
Usage with async/await

### ISSUE THREAD

**Issue by kopax** [pipedrive/client-nodejs#101] opened 2019-10-24 10:48 UTC
Hi guys, I see you still use `callback` for async call.

I'd like to know if we can use `async/await` instead of CB, is there a lib we can use for that?

**Comment by gutiju** [comment] 2019-10-30 14:46
Hi.

Yes, there are plans to do this (and some other enhancements) and priorities are under discussion. However and unfortunately we do not have an ETA yet. Please, see #81. Since this is a duplicate of that, I'm closing this issue.

**Closed by gutiju** 2019-10-30 14:46 UTC

**Comment by eerootsus** [comment] 2019-11-04 09:43
Duplicate of #81
