### ISSUE TITLE
Passing date objects makes requests fail

### ISSUE THREAD

**Issue by henry-all3dp** [pipedrive/client-nodejs#133] opened 2020-03-12 11:47 UTC
Requests requiring dates will fail with the current client version `10.2.2`.

Example: `ActivitiesController.addAnActivity` has a property `dueDate`. The documentation states: 'Due time of the activity in UTC. Format: HH:MM' and the property is described with `date("D M d, Y G:i")`. It is unclear which JavaScript type is required.

Reading the code the request will fail because of this test:
```javascript
    /**
     * Returns Datetime string value for field
     * @param  value  {object}  Datetime object
     * @param  type   {string}  The Datetime format of the date object (value) passed in
     * @returns       {string}  Stringified Datetime object
     */
    static stringifyDateTime(value, type) {
        if (value === null || value === undefined) {
            return null;
        }
        switch (type) {
        case 'unixtimestamp':
            return value.getTime();
        case 'rfc1123':
            return value.toUTCString();
        case 'rfc3339':
            return value.format();
        case 'date':
            return value.format('YYYY-MM-DD');
        default:
            return value.format('YYYY-MM-DD');
        }
    }
```

(the method is called with `type === 'date'`)

Before that it was possible to simply pass a string for `dueDate` in the format `'YYYY-MM-DD'` (the same format which is applied in the `format` method).

I cannot say which other controller methods are also affected, but it is breaking our current implementation. Please advise or fix the issue.

(Additional remark, with version `10.2.2` a breaking change was introduced that snake_case properties are overwritten with camel case properties in request payloads. It would have been great if this change would have been documented and the version been marked as a major version.)

**Comment by RuTsEST** [comment] 2020-03-16 13:58
Hey @henry-all3dp. Sorry for the late response. 
I'll start investigating your issue and will keep you updated on any advancements.

Regarding the breaking change, yes you are correct, it should have been marked as a major version even though from our side it was seen as a bug fix.

**Comment by ziimk** [comment] 2020-03-20 10:33
Hi @henry-all3dp - PR that should fix the problem is now open: https://github.com/pipedrive/client-nodejs/pull/139

Can you confirm it solves your issue? Thanks!

**Comment by henry-all3dp** [comment] 2020-03-20 11:02
@ziimk Thanks for fixing. I just did a few tests and can confirm that it works.

**Closed** 2020-03-20 12:40 UTC
