### ISSUE TITLE
Question: Difference between API v1 and this client

### ISSUE THREAD

**Issue by spaceben** [pipedrive/client-nodejs#190] opened 2021-05-08 21:16 UTC
The API allows to set `lead_id` of a `note`. This is not possible through the node client. Why?  

Should be around here:
https://github.com/pipedrive/client-nodejs/blob/95dda3a7ad21b525196705b95be4072b47df232a/src/api/NotesApi.js#L99

**Comment by siirimangus** [comment] 2021-05-20 12:24
Hey, @spaceben, good catch!
The issue is fixed in [version v11.0.0-rc.4](https://github.com/pipedrive/client-nodejs/releases/tag/v11.0.0-rc.4).

**Closed** 2021-05-20 14:05 UTC
